services:

    mongo-auth:
        container_name: mongo_db_auth
        image: mongo
        volumes:
          - mongo-data:/data/db
        ports:
          - "27017:27017"

    mongo-rest:
        container_name: mongo_db_rest
        image: mongo
        volumes:
          - mongo-data-rest:/data/db
        ports:
          - "27018:27017"
          
    cvutchat-socket:
      container_name: cvutchat-socket
      build: ./cvutchat-socket
      ports:
        - "3000:3000"
      depends_on:
        - mongo
      environment:
        AUTH_DB_URI: mongodb://mongo:27017/mydb
        REST_DB_URI: mongodb://mongo:27018/mydb

    cvutchat-rest:
        container_name: cvutchat-rest
        build: ./cvutchat-rest
        ports:
            - "3001:3001"
        depends_on:
            - mongo
        environment:
            REST_DB_URI: mongodb://mongo:27018/mydb

    cvutchat-auth:
        container_name: cvutchat-auth
        build: ./cvutchat-auth
        ports:
            - "3002:3002"
        depends_on:
            - mongo
        environment:
            AUTH_DB_URI: mongodb://mongo:27017/mydb

    cvutchat-frontend:
        container_name: cvutchat-frontend
        build: ./cvutchat-frontend
        ports:
            - "80:3000"
        depends_on:
            - cvutchat-rest
            - cvutchat-auth
            - cvutchat-socket
  
  volumes:
    mongo-data-auth:
    mongo-data-rest: