services:

  mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - mongo-data:/data/db
      - ./cvutchat-data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"

  data:
    container_name: cvutchat-data
    build: ./cvutchat-data
    depends_on:
      - mongo
    env_file:
      - cvutchat-data/.env

  rest:
    container_name: cvutchat-rest
    build: ./cvutchat-rest
    ports:
      - "3000:3000"
    depends_on:
      - data
  
  auth:
    container_name: cvutchat-auth
    build: ./cvutchat-auth
    depends_on:
      - rest

  socket:
    container_name: cvutchat-socket
    build: ./cvutchat-socket
    depends_on:
      - rest

  weather:
    container_name: cvutchat-weather
    build: ./cvutchat-weather
    depends_on:
      - rest

  frontend:
    container_name: cvutchat-frontend
    build: ./cvutchat-frontend
    depends_on:
      - rest
      - auth

volumes:
  mongo-data: