services:

    mongo:
        container_name: mongo_db
        image: mongo
        volumes:
          - mongo-data:/data/db
        ports:
          - "27017:27017"

    data:
        container_name: cvutchat-data
        build: ./cvutchat-data
        ports:
            - "3002:3002"
        depends_on:
            - mongo
        env_file:
            - cvutchat-data/.env

    rest:
        container_name: cvutchat-rest
        build: ./cvutchat-rest
        ports:
            - "3001:3001"
        depends_on:
            - data
          
    socket:
      container_name: cvutchat-socket
      build: ./cvutchat-socket
      ports:
        - "3000:3000"
      depends_on:
        - auth
        - rest

    auth:
        container_name: cvutchat-auth
        build: ./cvutchat-auth
        ports:
            - "5000:5000"
        depends_on:
            - socket
            - rest

    weather:
        container_name: cvutchat-weather
        build: ./cvutchat-weather
        ports:
            - "3003:3003"
        depends_on:
            - rest

    frontend:
        container_name: cvutchat-frontend
        build: ./cvutchat-frontend
        ports:
            - "80:3000"
        depends_on:
            - rest
            - auth
  
volumes:
  mongo-data:
